---
title: "Gene restriction"
author: "Aarón García Blázquez"
date: "2023-12-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
require(edgeR)
require(preprocessCore)
require(ggplot2)
require(tidyverse)
require(data.table)
require(knitr)
require(dplyr)
require(ggpubr)
require(ggdendro)
require(PCAtools)
require(tidyr)
require(tibble)
require(RColorBrewer)
require(sva)
require(limma)
```

```{r directories}
dir_docs <- "~/zebraheart-development/01-documentation/"
dir_src <- "~/zebraheart-development/02-scripts/"
dir_data <- "~/zebraheart-development/03-data/"
dir_output <- "~/zebraheart-development/04-output/"
```

```{r}
threshold <- 1000
```

## Data load

```{r}
counts <- read.table(file = paste0(dir_data,
                                   "datatables/",
                                   "datamatrix.txt"))
counts <- as.data.frame(counts[, order(colnames(counts),
                                       decreasing = TRUE)])
```

```{r}
phenodata <- read.table(file = paste0(dir_docs,
                                      "phenodata_4_groups.txt"),
                        sep = "\t",
                        header = TRUE,
                        row.names = 1)
phenodata <- as.data.frame(phenodata[order(rownames(phenodata),
                                           decreasing = TRUE), ])
phenodata$Sample <- rownames(phenodata)
```

## Data trimming

```{r}
datamatrix <- as.data.frame(counts[rowSums(counts) >= threshold, ])
```

### Exploratory Analysis

#### Boxplot

```{r}
group <- as.factor(phenodata$Set)

log2(datamatrix + 1) %>%
  rownames_to_column("Genes") %>%
  gather(Sample, Sample_value, -Genes) %>%
  left_join(phenodata, by = "Sample") %>%
  ggplot(aes(x = Sample, y = Sample_value, fill = Age)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

#### PCA

```{r}
p <- pca(datamatrix, metadata = phenodata)

biplot(p,
       colby = "Age",
       legendPosition = "right")
```

#### Clustering

```{r}
correlation <- cor(datamatrix)

distance <- as.dist((1 - correlation) / 2)

dd <- hclust(distance)

ddata_x <- dendro_data(dd)

ddata_x$labels <- merge(label(ddata_x),
                       phenodata,
                       by.x = "label",
                       by.y = "Sample")

dendroplot <- ggplot(segment(ddata_x)) +
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = label(ddata_x),
            aes(label = label, x = x, y = 0, colour = Age, hjust = 0)) +
  coord_flip() + scale_y_reverse(expand = c(0.2, 0)) +
  labs(color = "Age")

dendroplot
```

## Normalization

```{r}
# Create a DGEList object
dge_list <- DGEList(counts = datamatrix)

# Calculate library sizes and normalize for RNA composition
dge_list <- calcNormFactors(dge_list, method = "TMM")

# Get the normalized counts
tmm_counts <- as.data.frame(cpm(dge_list, log = FALSE))
```

### Exploratory Analysis

#### Boxplot

```{r}
group <- as.factor(phenodata$Set)

log2(tmm_counts + 1) %>%
  rownames_to_column("Genes") %>%
  gather(Sample, Sample_value, -Genes) %>%
  left_join(phenodata, by = "Sample") %>%
  ggplot(aes(x = Sample, y = Sample_value, fill = Age)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

#### PCA

```{r}
p <- pca(tmm_counts, metadata = phenodata)

biplot(p,
       colby = "Age",
       legendPosition = "right")
```

#### Clustering

```{r}
correlation <- cor(tmm_counts)

distance <- as.dist((1 - correlation) / 2)

dd <- hclust(distance)

ddata_x <- dendro_data(dd)

ddata_x$labels <- merge(label(ddata_x),
                       phenodata,
                       by.x = "label",
                       by.y = "Sample")

dendroplot <- ggplot(segment(ddata_x)) +
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = label(ddata_x),
            aes(label = label, x = x, y = 0, colour = Age, hjust = 0)) +
  coord_flip() + scale_y_reverse(expand = c(0.2, 0)) +
  labs(color = "Age")

dendroplot
```

## Batch effect removal

```{r}
mod0 <- model.matrix()
mod <- model.matrix(~0 + phenodata$Age, data = phenodata)
```

```{r}
mat <- limma::removeBatchEffect(tmm_counts, batch = phenodata$Set, design = mod)
```

### Exploratory Analysis

#### Boxplot

```{r}
group <- as.factor(phenodata$Set)

log2(datamatrix + 1) %>%
  rownames_to_column("Genes") %>%
  gather(Sample, Sample_value, -Genes) %>%
  left_join(phenodata, by = "Sample") %>%
  ggplot(aes(x = Sample, y = Sample_value, fill = Age)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

#### PCA

```{r}
p <- pca(datamatrix, metadata = phenodata)

biplot(p,
       colby = "Age",
       legendPosition = "right")
```

#### Clustering

```{r}
correlation <- cor(datamatrix)

distance <- as.dist((1 - correlation) / 2)

dd <- hclust(distance)

ddata_x <- dendro_data(dd)

ddata_x$labels <- merge(label(ddata_x),
                       phenodata,
                       by.x = "label",
                       by.y = "Sample")

dendroplot <- ggplot(segment(ddata_x)) +
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_text(data = label(ddata_x),
            aes(label = label, x = x, y = 0, colour = Age, hjust = 0)) +
  coord_flip() + scale_y_reverse(expand = c(0.2, 0)) +
  labs(color = "Age")

dendroplot
```






