---
title: "Intersection Analysis"
author: "Aarón García Blázquez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(png)
library(grid)
library(gridExtra)
```

```{r}
dir_venns <- "~/zebraheart-development/04-output/plots/venn_diagrams/"
```

# Normalization method

```{r}
img1 <- rasterGrob(readPNG(paste0(dir_venns, "venn_tmm_qn_72_48_up.png")))
img2 <- rasterGrob(readPNG(paste0(dir_venns, "venn_tmm_qn_72_48_down.png")))
img3 <- rasterGrob(readPNG(paste0(dir_venns, "venn_tmm_qn_120_72_up.png")))
img4 <- rasterGrob(readPNG(paste0(dir_venns, "venn_tmm_qn_120_72_down.png")))
img5 <- rasterGrob(readPNG(paste0(dir_venns, "venn_tmm_qn_adult_120_up.png")))
img6 <- rasterGrob(readPNG(paste0(dir_venns, "venn_tmm_qn_adult_120_down.png")))
```

```{r}
grid.arrange(img1, img2, img3, img4, img5, img6, ncol = 2, nrow = 3)
```

# non-coding RNA removal {.tabset}

## TMM

```{r}
img1 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_72_48_up.png")))
img2 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_72_48_down.png")))
img3 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_120_72_up.png")))
img4 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_120_72_down.png")))
img5 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_adult_120_up.png")))
img6 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_adult_120_down.png")))
```

```{r}
grid.arrange(img1, img2, img3, img4, img5, img6, ncol = 2, nrow = 3)
```

## TMM+QN

```{r}
img1 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_qn_72_48_up.png")))
img2 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_qn_72_48_down.png")))
img3 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_qn_120_72_up.png")))
img4 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_qn_120_72_down.png")))
img5 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_qn_adult_120_up.png")))
img6 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_qn_adult_120_down.png")))
```

```{r}
grid.arrange(img1, img2, img3, img4, img5, img6, ncol = 2, nrow = 3)
```

## TMM vs TMM+QN

```{r}
img1 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_qn_72_48_up.png")))
img2 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_qn_72_48_down.png")))
img3 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_qn_120_72_up.png")))
img4 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_qn_120_72_down.png")))
img5 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_qn_adult_120_up.png")))
img6 <- rasterGrob(readPNG(paste0(dir_venns, "venn_ncRNA_tmm_qn_adult_120_down.png")))
```

```{r}
grid.arrange(img1, img2, img3, img4, img5, img6, ncol = 2, nrow = 3)
```